# Generated by Django 3.1.6 on 2021-02-17 15:18

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 17, 15, 18, 54, 36452, tzinfo=utc)),
        ),
    ]
